CREATE DATABASE Quan_ly_ban_hang;
USE Quan_ly_ban_hang;

CREATE TABLE Customer(
cID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
cName VARCHAR(50),
cAge VARCHAR(3)
);

CREATE TABLE Orders(
oID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
oDate DATE,
oTotalPrice INT,
cID INT NOT NULL,
FOREIGN KEY (cID) REFERENCES Customer (cID)
);

CREATE TABLE Product(
pID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pName VARCHAR(50),
pPrice INT
);

CREATE TABLE OrderDetail(
odQTY INT,
oID INT,
pID INT,
FOREIGN KEY (oID) REFERENCES Orders (oID),
FOREIGN KEY (pID) REFERENCES Product (pID)
);


