CREATE DATABASE IF NOT EXISTS shopee;
USE shopee;
CREATE TABLE IF NOT EXISTS CATEGORY(
CATEGORY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CATEGORY_NAME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PRODUCT_NAME VARCHAR(50),
CATEGORY_ID INT,
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID)
);

CREATE TABLE IF NOT EXISTS VARIANT(
VARIANT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
VARIANT_NAME VARCHAR(50),
COLOR VARCHAR(50),
PRODUCT_ID INT,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);
CREATE TABLE IF NOT EXISTS CUSTOMER(
CUSTOMER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(50),
USER_PASSWORD VARCHAR(50),
EMAIL VARCHAR(50),
PHONE VARCHAR(10)
);
CREATE TABLE IF NOT EXISTS ADDRESS(
ADDRESS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ADDRESS_NUMBER INT,
STREET VARCHAR(50),
CUSTOMER_ID INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS CART(
CART_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TOTAL_PRICE INT,
CUSTOMER_ID INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS CART_LINE_ITEM(
CART_LINE_ITEM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TOTAL_PRICE INT,
QUANTITY INT,
CART_ID INT,
VARIANT_ID INT,
FOREIGN KEY (CART_ID) REFERENCES CART (CART_ID),
FOREIGN KEY (VARIANT_ID) REFERENCES VARIANT (VARIANT_ID)
);
select ADDRESS_ID, CUSTOMER_ID from ADDRESS
right join CUSTOMER C on C.CUSTOMER_ID = ADDRESS.CUSTOMER_ID;







