CREATE DATABASE dai_ly_ve_may_bay;
USE dai_ly_ve_may_bay;

CREATE TABLE Customer (
ID INT AUTO_INCREMENT PRIMARY KEY,
ACCOUNT VARCHAR(50),
PASSWORD VARCHAR(50)
);

CREATE TABLE UserID (
UserInfoID INT PRIMARY KEY,
GENDER VARCHAR(10),
NAME VARCHAR(50),
EMAIL VARCHAR(50),
ADDRESS VARCHAR(50),
DAYOFBIRTH VARCHAR(50),
PHONENUMBER VARCHAR(11)
);

CREATE TABLE flight_ticket(
ID INT AUTO_INCREMENT PRIMARY KEY,
position VARCHAR(5),
plane VARCHAR(5),
TIME VARCHAR(5),
SEAT VARCHAR(5),
DEPART VARCHAR(50),
DEST VARCHAR(50),
FLIGHTHOUR VARCHAR(50),
PRICE INT,
DATE DATE,
CUSTOMER_ID INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer (ID)
);